services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - static_volume:/usr/share/nginx/html/static

  backend:
    build: ./backend
    environment:
      - DEBUG=0
    volumes:
      - static_volume:/app/staticfiles
      - ./backend/db.sqlite3:/app/db.sqlite3  # Mount SQLite database file

volumes:
  static_volume: