# Generated by Django 5.2 on 2025-04-07 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("terminal", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Employee",
            new_name="User",
        ),
        migrations.DeleteModel(
            name="Client",
        ),
    ]
