# Generated by Django 5.2 on 2025-04-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("terminal", "0002_rename_employee_user_delete_client"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tasks",
            new_name="Service",
        ),
    ]
