# Generated by Django 5.2 on 2025-04-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terminal", "0003_rename_tasks_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee", models.BooleanField(default=False)),
            ],
        ),
    ]
