# Generated by Django 5.2 on 2025-04-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("terminal", "0004_role"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Role",
        ),
    ]
