# Generated by Django 5.2 on 2025-04-07 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terminal", "0005_delete_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="service",
            name="timestart",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="service",
            name="timestop",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
