# Generated by Django 5.2 on 2025-04-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terminal", "0007_myuser_alter_service_assigned_to_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
