# Generated by Django 5.2 on 2025-05-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0012_alter_appointment_time_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='service',
            name='time',
        ),
    ]
